cmake_minimum_required(VERSION 3.20)
project(FieldAnalysisPlugin LANGUAGES C CXX)
find_package(LLVM REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH "${LLVM_CMAKE_DIR}")
include(AddLLVM)
include_directories(SYSTEM ${LLVM_INCLUDE_DIRS})
add_definitions(${LLVM_DEFINITIONS})
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_llvm_pass_plugin(FieldAnalysis FieldAnalysisPass.cpp)
add_subdirectory(runtime)
