#!/usr/bin/env python3
"""
resolve_trace.py -- Translate access_trace.*.txt (field_id, addr) into
variable-level access sequence (struct.field_name, size).

Inputs:
  - access_trace.*.txt  (generated by instrumented program)
  - gep_field_map.json  (generated by FieldAnalysis pass)
  - struct_layout.json  (generated by FieldAnalysis pass)

Output:
  - variable_trace.*.txt  (one per access_trace.*.txt)

Format:
  struct.field_name  R/W/M  size  region

Usage:
  python3 resolve_trace.py <output_dir>
  python3 resolve_trace.py dfg/ --gep-map dfg/gep_field_map.json --layout dfg/struct_layout.json
"""

import argparse
import os
import re
from pathlib import Path

from field_analysis_utils import FieldMetadataLoader


def resolve_trace_file(trace_path, gep_map, struct_layout, loader, output_path):
    line_re = re.compile(
        r"\[?(\d+)\]?\s+(\d+)\s+([RWM])\s+(?:0x[0-9a-fA-F]+)\s+([SHG])"
    )

    with open(trace_path, "r") as fin, open(output_path, "w") as fout:
        for line in fin:
            line = line.strip()
            if not line:
                continue
            m = line_re.match(line)
            if not m:
                continue
            fid = int(m.group(2))
            rw = m.group(3)
            region = m.group(4)

            name = loader.get_field_name(fid, gep_map, struct_layout)
            size = loader.get_field_size(fid, gep_map, struct_layout)

            fout.write(f"{name}  {rw}  {size}  {region}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Translate access_trace.*.txt into variable-level access sequence"
    )
    parser.add_argument(
        "path", nargs="?", default=".",
        help="Directory containing access_trace.*.txt files (default: current dir)"
    )
    parser.add_argument(
        "--gep-map", default="gep_field_map.json",
        help="Path to gep_field_map.json (default: gep_field_map.json in path)"
    )
    parser.add_argument(
        "--layout", default="struct_layout.json",
        help="Path to struct_layout.json (default: struct_layout.json in path)"
    )
    parser.add_argument(
        "--output-dir", default=None,
        help="Output directory for variable_trace files (default: same as path)"
    )
    parser.add_argument(
        "--keep-timestamps", action="store_true",
        help="Keep [n] timestamps in output"
    )
    parser.add_argument(
        "--strict", action="store_true",
        help="Raise exceptions on missing files instead of warnings"
    )
    args = parser.parse_args()

    base = Path(args.path)
    gep_map_path = Path(args.gep_map)
    layout_path = Path(args.layout)

    if not gep_map_path.is_absolute():
        gep_map_path = base / gep_map_path
    if not layout_path.is_absolute():
        layout_path = base / layout_path

    loader = FieldMetadataLoader(strict=args.strict)

    if not gep_map_path.exists():
        print(f"[ERROR] gep_field_map.json not found: {gep_map_path}")
        return 1
    if not layout_path.exists():
        print(f"[WARN] struct_layout.json not found: {layout_path}")

    gep_map = loader.load_gep_field_map(str(gep_map_path))

    struct_layout = {}
    if layout_path.exists():
        struct_layout = loader.load_struct_layout(str(layout_path))

    trace_files = sorted(base.glob("access_trace.*.txt"))
    if not trace_files:
        print("[ERROR] No access_trace.*.txt files found")
        return 1

    output_base = Path(args.output_dir) if args.output_dir else base
    output_base.mkdir(parents=True, exist_ok=True)

    for tf in trace_files:
        suffix = tf.name[len("access_trace."):]
        output_name = f"variable_trace.{suffix}"
        output_path = output_base / output_name
        resolve_trace_file(tf, gep_map, struct_layout, loader, output_path)
        print(f"[OK] {tf.name} -> {output_path}")

    return 0


if __name__ == "__main__":
    exit(main())
