#!/usr/bin/env python3
"""
resolve_trace.py -- Translate access_trace.*.txt (field_id, addr) into
variable-level access sequence (struct.field_name, size).

Inputs:
  - access_trace.*.txt  (generated by instrumented program)
  - gep_field_map.json  (generated by FieldAnalysis pass)
  - struct_layout.json  (generated by FieldAnalysis pass)

Output:
  - variable_trace.*.txt  (one per access_trace.*.txt)

Format:
  struct.field_name  R/W/M  size  region

Usage:
  python3 resolve_trace.py <output_dir>
  python3 resolve_trace.py dfg/ --gep-map dfg/gep_field_map.json --layout dfg/struct_layout.json
"""

import argparse
import json
import os
import re
from pathlib import Path

SCALAR_SIZES = {
    "float": 4,
    "double": 8,
    "i8": 1,
    "i16": 2,
    "i32": 4,
    "i64": 8,
    "ptr": 8,
    "unknown": 0,
}


def load_gep_field_map(path):
    with open(path, "r") as f:
        raw = json.load(f)
    id_to_info = {}
    for entry in raw:
        fid = entry.get("field_id") or entry.get("id")
        if fid is not None:
            id_to_info[int(fid)] = entry
    return id_to_info


def load_struct_layout(path):
    with open(path, "r") as f:
        return json.load(f)


def get_field_size(fid, id_to_info, struct_layout):
    info = id_to_info.get(fid)
    if not info:
        return 0

    struct_name = info.get("struct_name", "")
    field_idx = info.get("field_idx", 0)

    if struct_name and struct_name.startswith("scalar."):
        type_name = struct_name[len("scalar."):]
        return SCALAR_SIZES.get(type_name, 0)

    structs = struct_layout.get("structs", {})
    st = structs.get(struct_name)
    if not st:
        return 0

    fields = st.get("fields", [])
    if field_idx < len(fields):
        return fields[field_idx].get("size", 0)

    return 0


def get_field_name(fid, id_to_info):
    info = id_to_info.get(fid)
    if not info:
        return f"unknown_{fid}"

    struct_name = info.get("struct_name", "unknown")
    field_idx = info.get("field_idx", 0)

    if struct_name.startswith("scalar."):
        return struct_name

    field_names = info.get("field_names", [])
    if field_idx < len(field_names):
        return f"{struct_name}.{field_names[field_idx]}"

    return f"{struct_name}.field_{field_idx}"


def resolve_trace_file(trace_path, id_to_info, struct_layout, output_path, skip_timestamps=True):
    line_re = re.compile(
        r"\[?(\d+)\]?\s+(\d+)\s+([RWM])\s+(?:0x[0-9a-fA-F]+)\s+([SHG])"
    )

    with open(trace_path, "r") as fin, open(output_path, "w") as fout:
        for line in fin:
            line = line.strip()
            if not line:
                continue
            m = line_re.match(line)
            if not m:
                continue
            fid = int(m.group(2))
            rw = m.group(3)
            region = m.group(4)

            name = get_field_name(fid, id_to_info)
            size = get_field_size(fid, id_to_info, struct_layout)

            fout.write(f"{name}  {rw}  {size}  {region}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Translate access_trace.*.txt into variable-level access sequence"
    )
    parser.add_argument(
        "path", nargs="?", default=".",
        help="Directory containing access_trace.*.txt files (default: current dir)"
    )
    parser.add_argument(
        "--gep-map", default="gep_field_map.json",
        help="Path to gep_field_map.json (default: gep_field_map.json in path)"
    )
    parser.add_argument(
        "--layout", default="struct_layout.json",
        help="Path to struct_layout.json (default: struct_layout.json in path)"
    )
    parser.add_argument(
        "--output-dir", default=None,
        help="Output directory for variable_trace files (default: same as path)"
    )
    parser.add_argument(
        "--keep-timestamps", action="store_true",
        help="Keep [n] timestamps in output"
    )
    args = parser.parse_args()

    base = Path(args.path)
    gep_map_path = Path(args.gep_map)
    layout_path = Path(args.layout)

    if not gep_map_path.is_absolute():
        gep_map_path = base / gep_map_path
    if not layout_path.is_absolute():
        layout_path = base / layout_path

    if not gep_map_path.exists():
        print(f"[ERROR] gep_field_map.json not found: {gep_map_path}")
        return 1
    if not layout_path.exists():
        print(f"[WARN] struct_layout.json not found: {layout_path}")

    id_to_info = load_gep_field_map(gep_map_path)

    struct_layout = {}
    if layout_path.exists():
        struct_layout = load_struct_layout(layout_path)

    trace_files = sorted(base.glob("access_trace.*.txt"))
    if not trace_files:
        print("[ERROR] No access_trace.*.txt files found")
        return 1

    output_base = Path(args.output_dir) if args.output_dir else base
    output_base.mkdir(parents=True, exist_ok=True)

    for tf in trace_files:
        suffix = tf.name[len("access_trace."):]
        output_name = f"variable_trace.{suffix}"
        output_path = output_base / output_name
        resolve_trace_file(tf, id_to_info, struct_layout, output_path, not args.keep_timestamps)
        print(f"[OK] {tf.name} -> {output_path}")

    return 0


if __name__ == "__main__":
    exit(main())